version: "3.8"
services:
  my-sql:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=forum
    #    volumes:
    #      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3316:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
