version: "3.8"
networks:
  back-tier:

services:
  my-sql:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=forum
    #    volumes:
    #      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3316:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - back-tier
  grafana:
    image: grafana/grafana-oss:10.1.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    user: "root"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - back-tier
